"use client";
import { useState } from "react";
import { AlertCircle, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { TractionRecord } from "@/lib/traction-model";

const roles=[{id:"leitor",name:"Leitor"},{id:"responsavel",name:"Responsável por iniciativa"},{id:"gestor",name:"Gestor de área"},{id:"direcao",name:"Direção"},{id:"admin",name:"Administrador"}];
export function AccessForm({email,role,area,editing,saving,areas,roleDescription,onEmail,onRole,onArea,onSave,onCancel}:{email:string;role:string;area:string;editing:boolean;saving:boolean;areas:TractionRecord[];roleDescription:string;onEmail:(value:string)=>void;onRole:(value:string)=>void;onArea:(value:string)=>void;onSave:()=>Promise<void>;onCancel:()=>void}) {
  const [attempted,setAttempted]=useState(false);
  const [error,setError]=useState("");
  const invalidEmail=!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
  const needsArea=["gestor","responsavel"].includes(role);
  async function save(){setAttempted(true);if(invalidEmail || needsArea && !area) return;setError("");try{await onSave();}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível salvar o acesso. Tente novamente.");}}
  return <form className="access-studio" noValidate onSubmit={event=>{event.preventDefault();if(!saving)void save();}}>
    <div className="access-studio-body"><div className="record-fields"><div className="record-field record-field-wide"><label htmlFor="access-email">Email da pessoa<span>Obrigatório</span></label><Input id="access-email" type="email" inputMode="email" autoComplete="email" autoFocus value={email} disabled={saving||editing} placeholder="nome@empresa.com" onChange={event=>{onEmail(event.target.value);setError("");}} aria-required="true" aria-invalid={attempted&&invalidEmail} aria-describedby={attempted&&invalidEmail?"access-email-error":undefined}/>{attempted&&invalidEmail && <small id="access-email-error" className="record-field-error">Informe um email válido.</small>}</div><div className="record-field record-field-wide"><label htmlFor="access-role">Função na empresa<span>Obrigatório</span></label><Select value={role} onValueChange={onRole} disabled={saving}><SelectTrigger id="access-role"><SelectValue/></SelectTrigger><SelectContent>{roles.map(item=><SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div>{needsArea && <div className="record-field record-field-wide"><label htmlFor="access-area">Área de atuação<span>Obrigatório</span></label><Select value={area||"none"} onValueChange={value=>onArea(value==="none"?"":value)} disabled={saving||!areas.length}><SelectTrigger id="access-area" aria-required="true" aria-invalid={attempted&&!area}><SelectValue placeholder="Selecione a área"/></SelectTrigger><SelectContent><SelectItem value="none">Selecione a área</SelectItem>{areas.map(item=><SelectItem key={item.id} value={item.id}>{item.title}</SelectItem>)}</SelectContent></Select>{!areas.length && <small className="record-field-help">Cadastre uma área em Áreas e cargos antes de atribuir essa função.</small>}{attempted&&!area && <small className="record-field-error">Selecione a área da pessoa.</small>}</div>}</div>
    <section className="access-permission-card" aria-label="Prévia das permissões"><ShieldCheck size={22}/><div><h3>{roles.find(item=>item.id===role)?.name}</h3><p>{roleDescription}</p>{needsArea&&area&&<small>Área: {areas.find(item=>item.id===area)?.title}</small>}</div></section><p className="record-field-help">Se a pessoa ainda não tiver conta, a senha inicial será mostrada uma única vez. Nenhum email é enviado automaticamente.</p>{error&&<p className="record-studio-error" role="alert"><AlertCircle size={18}/>{error}</p>}</div><footer className="record-studio-footer"><Button type="button" variant="outline" disabled={saving} onClick={onCancel}>Cancelar</Button><div><Button type="submit" className="action-primary" disabled={saving}>{saving?"Salvando…":"Salvar acesso"}</Button></div></footer>
  </form>;
}
