"use client";

import { useState } from "react";
import { ArrowUpRight, BookOpenCheck, BriefcaseBusiness, Building2, CheckCircle2, ClipboardCheck, GitBranch, Lightbulb, Plus, ShieldCheck, Sparkles, TrendingUp, Users, UserRoundCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { RecordKind, TractionRecord } from "@/lib/traction-model";
import type { SectionProps } from "./traction-types";
import { TractionReportView } from "./traction-report-view";
import { StrategyOverview, StrategyPlanning, StrategyReviews } from "./traction-strategy";
import { TractionAdmin } from "./traction-admin";
import { TractionInsightBoard } from "./traction-insight-board";
import { TractionGuide } from "./traction-guide";
import { ModuleStart } from "./traction-module-start";
import { TeamModule, HirePersonButton } from "./traction-team";
import { VacancyBoard, vacancyStages } from "./traction-vacancy-board";

const ofKind = (records: TractionRecord[], kind: RecordKind) => records.filter((record) => record.kind === kind && !record.archived_at);
const date = (value?: string) => value ? new Date(`${value.slice(0, 10)}T12:00:00`).toLocaleDateString("pt-BR") : "Sem data";
const nameOf = (records: TractionRecord[], id?: string) => records.find((record) => record.id === id)?.title || "Não vinculado";
const statusClass = (status: string) => ["Atenção", "Aberto", "Pendente", "Não avançar"].includes(status) ? "status-warning" : ["Concluída", "Concluído", "Resolvido", "Fechada"].includes(status) ? "status-success" : "status-neutral";

function Status({ value }: { value?: string }) { return value ? <span className={`status-tag ${statusClass(value)}`}>{value}</span> : null; }
function Panel({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`panel ${className}`}>{children}</section>; }
function PanelHead({ eyebrow, title, note, action }: { eyebrow?: string; title: string; note?: string; action?: React.ReactNode }) { return <div className="panel-head"><div>{eyebrow && <span className="section-label">{eyebrow}</span>}<h2>{title}</h2>{note && <p>{note}</p>}</div>{action}</div>; }
function Empty({ icon, title, text, action }: { icon: React.ReactNode; title: string; text: string; action?: React.ReactNode }) { return <div className="empty-panel"><div className="empty-icon">{icon}</div><strong>{title}</strong><p>{text}</p>{action}</div>; }
function CreateButton({ kind, label, props, personType }: { kind: RecordKind; label: string; props: SectionProps; personType?: "Candidato" | "Colaborador" }) { return props.canCreate(kind) ? <Button className="action-primary" size="sm" onClick={() => props.onCreate(kind, personType)}><Plus size={15} />{label}</Button> : null; }
function RecordLine({ record, records, onOpen, eyebrow, detail }: { record: TractionRecord; records: TractionRecord[]; onOpen: (record: TractionRecord) => void; eyebrow?: string; detail?: string }) { return <button className="record-line" onClick={() => onOpen(record)}><div><small>{eyebrow || (record.data.areaId ? nameOf(records, record.data.areaId) : "REGISTRO")}</small><strong>{record.title}</strong><span>{detail || record.data.outcome || record.data.mission || record.data.reason || record.data.evidence || record.data.summary || "Abrir detalhes"}</span></div><div className="record-line-end"><Status value={record.data.status || record.data.decision} /><ArrowUpRight size={17} /></div></button>; }
function Metric({ icon, label, value, foot }: { icon: React.ReactNode; label: string; value: number | string; foot: string }) { return <div className="metric"><span className="metric-icon">{icon}</span><span className="metric-label">{label}</span><strong>{value}</strong><small>{foot}</small></div>; }

export function WorkspaceSections(props: SectionProps) {
  switch (props.section) {
    case "team": return <TeamModule {...props} />;
    case "overview": return <StrategyOverview {...props} />;
    case "guide": return <TractionGuide {...props} />;
    case "planning": return <StrategyPlanning {...props} />;
    case "structure": return <Structure {...props} />;
    case "hiring": return <Hiring {...props} />;
    case "promotions": return <Promotions {...props} />;
    case "reviews": return <StrategyReviews {...props} />;
    case "results": return <TractionReportView key={props.workspace?.organization.id || "demo"} {...props} />;
    case "admin": return <TractionAdmin key={props.workspace?.organization.id || "demo"} {...props} />;
  }
}

function Structure(props: SectionProps) {
  const { records, onOpen } = props;
  const areas = ofKind(records, "area"), roles = ofKind(records, "role");
  const [query, setQuery] = useState("");
  const [areaId, setAreaId] = useState("all");
  const visibleAreas = areas.filter((area) => (areaId === "all" || area.id === areaId) && `${area.title} ${area.data.mission} ${area.data.lead}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")));
  const visibleRoles = roles.filter((role) => (areaId === "all" || role.data.areaId === areaId) && `${role.title} ${role.data.mission} ${role.data.competencies} ${role.data.criteria}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")));
  const completeness = roles.length ? Math.round(100 * roles.filter((role) => role.data.mission && role.data.competencies && role.data.criteria).length / roles.length) : 0;
  if (props.demo) return <ModuleStart module="structure" onCreateOrganization={props.onCreateOrganization} onNavigate={props.onNavigate} />;
  return <div className="section-stack"><TractionInsightBoard {...props} mode="structure" /><div className="structure-summary"><div><span className="summary-icon"><GitBranch size={22} /></span><div><strong>{areas.length}</strong><span>{areas.length === 1 ? "área cadastrada" : "áreas cadastradas"}</span></div></div><div><span className="summary-icon"><BriefcaseBusiness size={22} /></span><div><strong>{roles.length}</strong><span>{roles.length === 1 ? "cargo estruturado" : "cargos estruturados"}</span></div></div><div><span className="summary-icon"><BookOpenCheck size={22} /></span><div><strong>{roles.length ? `${completeness}%` : "—"}</strong><span>{roles.length ? "cargos com critérios completos" : "sem cargos para avaliar"}</span></div></div></div>
    <div className="module-filter-row"><label>Buscar área ou cargo<Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nome, missão ou critério" /></label><label>Área<select value={areaId} onChange={(event) => setAreaId(event.target.value)}><option value="all">Todas as áreas</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.title}</option>)}</select></label><span>{visibleAreas.length} {visibleAreas.length === 1 ? "área" : "áreas"} · {visibleRoles.length} {visibleRoles.length === 1 ? "cargo" : "cargos"}</span></div>
    <div className="two-panels"><Panel><PanelHead eyebrow="MAPA ORGANIZACIONAL" title="Áreas" note="Atribuições e liderança de cada equipe." action={<CreateButton kind="area" label="Nova área" props={props} />} /><div className="area-grid">{visibleAreas.length ? visibleAreas.map((area) => <button className="area-card" key={area.id} onClick={() => onOpen(area)}><div><Building2 size={19} /><span>{roles.filter((role) => role.data.areaId === area.id).length} {roles.filter((role) => role.data.areaId === area.id).length === 1 ? "cargo" : "cargos"}</span></div><strong>{area.title}</strong><p>{area.data.mission || "Missão a definir"}</p><small>{area.data.lead || "Responsável a definir"}</small></button>) : <Empty icon={<Building2 size={23} />} title={query || areaId !== "all" ? "Nenhuma área encontrada" : "Comece pelas áreas"} text={query || areaId !== "all" ? "Revise a busca ou selecione outra área." : "Defina o papel de cada equipe e sua liderança."} action={<CreateButton kind="area" label="Criar área" props={props} />} />}</div></Panel><Panel><PanelHead eyebrow="ARQUITETURA DE CARGOS" title="Cargos e níveis" note="Missão, resultados e critérios de evolução." action={<CreateButton kind="role" label="Novo cargo" props={props} />} />{visibleRoles.length ? <Table><TableHeader><TableRow><TableHead>Cargo</TableHead><TableHead>Área</TableHead><TableHead>Nível</TableHead><TableHead>Critérios</TableHead></TableRow></TableHeader><TableBody>{visibleRoles.map((role) => <TableRow key={role.id} className="clickable-row" role="button" tabIndex={0} aria-label={`Abrir cargo ${role.title}`} onClick={() => onOpen(role)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onOpen(role); } }}><TableCell><strong>{role.title}</strong><small>{role.data.mission || "Missão a definir"}</small></TableCell><TableCell>{nameOf(records, role.data.areaId)}</TableCell><TableCell>{role.data.level || "—"}</TableCell><TableCell>{role.data.criteria ? <span className="subtle-check"><CheckCircle2 size={14} /> Definidos</span> : <span className="subtle-pending">Pendente</span>}</TableCell></TableRow>)}</TableBody></Table> : <Empty icon={<BriefcaseBusiness size={23} />} title={query || areaId !== "all" ? "Nenhum cargo encontrado" : "Descreva o primeiro cargo"} text={query || areaId !== "all" ? "Revise a busca ou selecione outra área." : "Uma boa descrição conecta tarefas, competências e resultados."} action={<CreateButton kind="role" label="Criar cargo" props={props} />} />}</Panel></div>
    <div className="insight-strip"><Lightbulb size={18} /><span>As descrições de cargo orientam vagas, entrevistas e promoções. Revise os critérios com especialistas da própria área.</span></div>
  </div>;
}

function Hiring(props: SectionProps) {
  const { records, onOpen } = props;
  const vacancies = ofKind(records, "vacancy"), candidates = ofKind(records, "person").filter((record) => record.data.type === "Candidato"), assessments = ofKind(records, "assessment").filter((record) => record.data.type === "Contratação");
  const [query, setQuery] = useState("");
  const [stage, setStage] = useState("all");
  const matches = (text: string) => text.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"));
  const visibleVacancies = vacancies.filter((record) => (stage === "all" || (record.data.status || "Planejada") === stage) && matches(`${record.title} ${record.data.reason} ${nameOf(records, record.data.roleId)}`));
  const matchesStage = (vacancyId?: string) => stage === "all" || vacancies.some(vacancy => vacancy.id === vacancyId && (vacancy.data.status || "Planejada") === stage);
  const visibleCandidates = candidates.filter((record) => matchesStage(record.data.vacancyId) && matches(`${record.title} ${nameOf(records, record.data.vacancyId)} ${record.data.status}`));
  const visibleAssessments = assessments.filter((record) => matchesStage(record.data.vacancyId || candidates.find(person => person.id === record.data.personId)?.data.vacancyId) && matches(`${record.title} ${nameOf(records, record.data.personId)} ${record.data.evidence} ${record.data.criteriaEvidence}`));
  const nextStep = (record: TractionRecord) => !record.data.roleId ? "Vincular cargo" : !record.data.interviewQuestions || !record.data.interviewRubric ? "Preparar entrevista" : record.data.status === "Decisão" ? "Registrar decisão humana" : record.data.status === "Fechada" ? "Consultar resultado" : "Acompanhar candidaturas";
  const stages = vacancyStages;
  if (props.demo) return <ModuleStart module="hiring" onCreateOrganization={props.onCreateOrganization} onNavigate={props.onNavigate} />;
  return <div className="section-stack"><TractionInsightBoard {...props} mode="hiring" /><div className="section-toolbar"><p>Vagas, candidaturas e avaliações vinculadas ao cargo.</p><CreateButton kind="vacancy" label="Nova vaga" props={props} /></div><div className="module-filter-row"><label>Buscar no processo<Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Vaga, pessoa ou evidência" /></label><label>Etapa da vaga<select value={stage} onChange={(event) => setStage(event.target.value)}><option value="all">Todas as etapas</option>{stages.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><span>{visibleVacancies.length} {visibleVacancies.length === 1 ? "vaga" : "vagas"} · {visibleCandidates.length} {visibleCandidates.length === 1 ? "candidatura" : "candidaturas"}</span></div><VacancyBoard vacancies={vacancies} stage={stage} query={query} nextStep={nextStep} {...props} />
    <div className="two-panels"><Panel><PanelHead eyebrow="PESSOAS CANDIDATAS" title="Candidaturas" note="Vincule cada pessoa à vaga em análise." action={<CreateButton kind="person" label="Adicionar candidato" personType="Candidato" props={props} />} />{visibleCandidates.length ? visibleCandidates.map((record) => <div className="team-candidate-row" key={record.id}><RecordLine record={record} records={records} onOpen={onOpen} eyebrow={nameOf(records, record.data.vacancyId).toUpperCase()} detail={record.data.status || "Etapa não informada"} /><HirePersonButton person={record} props={props} /></div>) : <Empty icon={<Users size={23} />} title={query || stage !== "all" ? "Nenhuma candidatura encontrada" : "Sem candidatos"} text={query || stage !== "all" ? "Ajuste a busca ou a etapa para localizar uma pessoa ou vaga." : "Adicione uma pessoa e a vaga correspondente."} />}</Panel><Panel><PanelHead eyebrow="ENTREVISTAS" title="Avaliações de contratação" note="Compare evidências com os mesmos critérios do cargo." action={<CreateButton kind="assessment" label="Nova avaliação" personType="Candidato" props={props} />} />{visibleAssessments.length ? visibleAssessments.map((record) => <RecordLine key={record.id} record={record} records={records} onOpen={onOpen} eyebrow={nameOf(records, record.data.roleId).toUpperCase()} detail={`${record.data.decision || "Decisão pendente"} · ${record.data.criteriaEvidence || record.data.evidence || "Evidência pendente"}`} />) : <Empty icon={<ClipboardCheck size={23} />} title={query || stage !== "all" ? "Nenhuma avaliação encontrada" : "Sem avaliações"} text={query || stage !== "all" ? "Ajuste a busca ou a etapa para localizar entrevista ou evidência." : "Registre evidências da entrevista ou de uma amostra de trabalho."} />}</Panel></div>
    <div className="method-strip"><ShieldCheck size={18} /><span>Prepare perguntas e critérios antes da entrevista. Registre evidências do trabalho; a decisão final cabe à equipe.</span><a href="https://www.opm.gov/policy-data-oversight/assessment-and-selection/structured-interviews" target="_blank" rel="noreferrer">Ver referência <ArrowUpRight size={14} /></a></div>
  </div>;
}

function Promotions(props: SectionProps) {
  const { records, onOpen } = props;
  const employees = ofKind(records, "person").filter((record) => record.data.type === "Colaborador"), assessments = ofKind(records, "assessment").filter((record) => record.data.type === "Promoção"), development = ofKind(records, "development");
  const [query, setQuery] = useState("");
  const visibleAssessments = assessments.filter((assessment) => {
    const person = records.find((record) => record.id === assessment.data.personId);
    return `${person?.title} ${nameOf(records, person?.data.currentRoleId)} ${nameOf(records, assessment.data.roleId)} ${assessment.data.evidence} ${assessment.data.criteriaEvidence}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"));
  });
  if (props.demo) return <ModuleStart module="promotions" onCreateOrganization={props.onCreateOrganization} onNavigate={props.onNavigate} />;
  return <div className="section-stack"><TractionInsightBoard {...props} mode="promotions" />
    <div className="metric-grid three"><Metric icon={<Users size={20} />} label="Colaboradores" value={employees.length} foot="Na estrutura atual" /><Metric icon={<Sparkles size={20} />} label="Promoções em análise" value={assessments.filter((record) => !record.data.decision || record.data.decision === "Em análise").length} foot="Com decisão pendente" /><Metric icon={<TrendingUp size={20} />} label="Planos de evolução" value={development.length} foot="Ações acompanhadas" /></div>
    <Panel><PanelHead eyebrow="EVOLUÇÃO INTERNA" title="Do cargo atual ao próximo passo" note="Critérios e evidências apoiam a conversa. A decisão é sempre da equipe." action={<CreateButton kind="assessment" label="Nova avaliação" personType="Colaborador" props={props} />} /><div className="module-filter-row"><label>Buscar pessoa ou cargo<Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nome, cargo ou evidência" /></label><span>{visibleAssessments.length} {visibleAssessments.length === 1 ? "avaliação" : "avaliações"}</span></div>{visibleAssessments.length ? <div className="table-scroll"><Table><TableHeader><TableRow><TableHead>Pessoa</TableHead><TableHead>Cargo atual → pretendido</TableHead><TableHead>Critérios e evidências</TableHead><TableHead>Decisão</TableHead></TableRow></TableHeader><TableBody>{visibleAssessments.map((assessment) => { const person = records.find((record) => record.id === assessment.data.personId); const target = records.find((record) => record.id === assessment.data.roleId); return <TableRow key={assessment.id} className="clickable-row" role="button" tabIndex={0} onClick={() => onOpen(assessment)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onOpen(assessment); } }}><TableCell><strong>{person?.title || "Pessoa não vinculada"}</strong><small>{assessment.data.assessedAt ? date(assessment.data.assessedAt) : "Sem data"}</small></TableCell><TableCell>{nameOf(records, person?.data.currentRoleId)} → {target?.title || "Cargo alvo não vinculado"}</TableCell><TableCell><strong>{target?.data.criteria || "Critérios do cargo pendentes"}</strong><small>{assessment.data.criteriaEvidence || assessment.data.evidence || "Evidência pendente"}</small></TableCell><TableCell><Status value={assessment.data.decision || "Em análise"} /></TableCell></TableRow>; })}</TableBody></Table></div> : <Empty icon={<UserRoundCheck size={23} />} title={query ? "Nenhuma avaliação encontrada" : "Ainda não há avaliações"} text={query ? "Ajuste a busca para localizar a pessoa ou o cargo." : "Registre o cargo pretendido e as evidências observadas antes da decisão."} />}</Panel>
    <div className="two-panels"><Panel><PanelHead eyebrow="PESSOAS" title="Colaboradores" note="Área e cargo atual de cada pessoa." action={<CreateButton kind="person" label="Adicionar colaborador" personType="Colaborador" props={props} />} />{employees.length ? employees.map((record) => <RecordLine key={record.id} record={record} records={records} onOpen={onOpen} eyebrow={nameOf(records, record.data.areaId).toUpperCase()} detail={nameOf(records, record.data.currentRoleId)} />) : <Empty icon={<Users size={23} />} title="Cadastre um colaborador" text="Registre sua área e seu cargo atual." />}</Panel><Panel><PanelHead eyebrow="DESENVOLVIMENTO" title="Planos e próximos passos" note="Cada ação precisa de responsável e prazo." action={<CreateButton kind="development" label="Novo plano" props={props} />} />{development.length ? development.map((record) => <button key={record.id} className="record-line" onClick={() => onOpen(record)}><div><small>{nameOf(records, record.data.personId).toUpperCase()} · {nameOf(records, record.data.roleId)}</small><strong>{record.title}</strong><span>{record.data.action || record.data.goal || "Ação a definir"}</span><span>Responsável: {record.data.owner || "a definir"} · Prazo: {date(record.data.due)}</span></div><div className="record-line-end"><Status value={record.data.status} /><ArrowUpRight size={17} /></div></button>) : <Empty icon={<BookOpenCheck size={23} />} title="Sem planos" text="Crie ações específicas para apoiar a evolução." />}</Panel></div>
  </div>;
}
