import type { RecordKind, TractionRecord } from "@/lib/traction-model";

export type FormField = {
  key: string;
  label: string;
  type?: "text" | "textarea" | "date" | "select";
  options?: { value: string; label: string }[];
  placeholder?: string;
  required?: boolean;
  hint?: string;
};

const fixed = (values: string[]) => values.map((value) => ({ value, label: value }));

export function formSpec(kind: RecordKind, records: TractionRecord[], personType: "Candidato" | "Colaborador", data: Record<string, string> = {}, ownId?: string) {
  const options = (target: RecordKind, filter?: (record: TractionRecord) => boolean) => records.filter((record) => record.kind === target && record.id !== ownId && !record.archived_at && (!filter || filter(record))).map((record) => ({ value: record.id, label: record.title }));
  const linked = (id?: string) => records.find((record) => record.id === id);
  const fields: Record<RecordKind, FormField[]> = {
    cycle: [
      { key: "startDate", label: "Início", type: "date", required: true },
      { key: "endDate", label: "Fim", type: "date", required: true },
      { key: "status", label: "Situação", type: "select", options: fixed(["Planejado", "Ativo", "Encerrado"]) },
      { key: "description", label: "Contexto do ciclo", type: "textarea", placeholder: "O que a empresa precisa alcançar neste período?" },
      { key: "vision", label: "Norte estratégico", type: "textarea", placeholder: "Qual direção orienta este ciclo?" },
      { key: "cadence", label: "Frequência das revisões", type: "select", options: fixed(["Semanal", "Quinzenal", "Mensal"]) },
      { key: "learnings", label: "Aprendizados do encerramento", type: "textarea", hint: "Obrigatório ao encerrar o ciclo. Compare os resultados alcançados com os alvos." },
      { key: "carryForward", label: "O que levar ao próximo ciclo", type: "textarea" },
    ],
    objective: [
      { key: "cycleId", label: "Ciclo", type: "select", options: options("cycle"), required: true },
      { key: "owner", label: "Responsável executivo", required: true },
      { key: "ownerEmail", label: "Email do responsável" },
      { key: "description", label: "Direção e justificativa", type: "textarea" },
      { key: "rationale", label: "Por que este objetivo importa?", type: "textarea" },
      { key: "dependsOnId", label: "Depende de outro objetivo", type: "select", options: options("objective", (record) => !data.cycleId || record.data.cycleId === data.cycleId) },
      { key: "status", label: "Situação", type: "select", options: fixed(["Ativo", "Concluído", "Suspenso"]) },
    ],
    area: [
      { key: "parentAreaId", label: "Área superior", type: "select", options: options("area") },
      { key: "lead", label: "Responsável pela área" },
      { key: "mission", label: "Papel da área", type: "textarea", placeholder: "Qual resultado esta equipe entrega?" },
    ],
    role: [
      { key: "areaId", label: "Área", type: "select", options: options("area"), required: true },
      { key: "level", label: "Nível", type: "select", options: fixed(["Estágio", "Júnior", "Pleno", "Sênior", "Especialista", "Coordenação", "Gerência", "Direção"]) },
      { key: "mission", label: "Missão do cargo", type: "textarea", placeholder: "Por que o cargo existe?" },
      { key: "outcomes", label: "Resultados esperados", type: "textarea", placeholder: "Um resultado observável por linha" },
      { key: "competencies", label: "Competências essenciais", type: "textarea", placeholder: "Conhecimentos e comportamentos ligados ao trabalho" },
      { key: "successMeasures", label: "Como medir sucesso", type: "textarea" },
      { key: "criteria", label: "Critérios de evolução", type: "textarea", placeholder: "O que distingue um bom desempenho neste nível?" },
    ],
    priority: [
      { key: "cycleId", label: "Ciclo", type: "select", options: options("cycle"), required: true },
      { key: "objectiveId", label: "Objetivo estratégico", type: "select", options: options("objective", (record) => !data.cycleId || record.data.cycleId === data.cycleId), required: true },
      { key: "areaId", label: "Área", type: "select", options: options("area") },
      { key: "outcome", label: "Mudança esperada", type: "textarea", placeholder: "Qual mudança estratégica buscamos? Defina o indicador no resultado vinculado." },
      { key: "rationale", label: "Justificativa", type: "textarea" },
      { key: "impact", label: "Impacto esperado", type: "textarea" },
      { key: "inScope", label: "Dentro do escopo", type: "textarea" },
      { key: "outOfScope", label: "Fora do escopo", type: "textarea" },
      { key: "position", label: "Ordem no ciclo", placeholder: "Ex.: 1" },
      { key: "owner", label: "Responsável", required: true },
      { key: "ownerEmail", label: "Email do responsável", hint: "Use o email de alguém com acesso à empresa para solicitar atualizações." },
      { key: "due", label: "Prazo", type: "date" },
      { key: "status", label: "Situação", type: "select", options: fixed(["Planejada", "Em andamento", "Atenção", "Concluída"]) },
      { key: "riskReason", label: "Motivo da atenção", type: "textarea", hint: "Obrigatório quando a situação for Atenção." },
      { key: "nextAction", label: "Próxima ação", type: "textarea", hint: "Obrigatória quando a situação for Atenção." },
      { key: "changeReason", label: "Justificativa da mudança", type: "textarea", hint: "Obrigatória ao mudar alvo ou ordem; fica registrada no histórico." },
      { key: "closeOutcome", label: "Resultado no encerramento", type: "select", options: fixed(["Concluída", "Interrompida", "Transferida"]) },
    ],
    result: [
      { key: "priorityId", label: "Prioridade", type: "select", options: options("priority"), required: true },
      { key: "outcome", label: "Resultado esperado", type: "textarea", required: true, placeholder: "Qual mudança será observável?" },
      { key: "indicator", label: "Indicador", required: true, placeholder: "Ex.: tempo médio de contratação" },
      { key: "indicatorKind", label: "O que este indicador mede?", type: "select", options: fixed(["Resultado", "Atividade"]), required: true, hint: "Resultado mede uma mudança alcançada; atividade mede o trabalho realizado para chegar lá." },
      { key: "measureType", label: "Tipo de evidência", type: "select", options: fixed(["Número", "Verificável"]), required: true },
      { key: "direction", label: "Direção desejada", type: "select", options: fixed(["Aumentar", "Reduzir", "Manter"]) },
      { key: "baseline", label: "Valor inicial", required: true },
      { key: "target", label: "Alvo", required: true },
      { key: "unit", label: "Unidade", required: true, placeholder: "Ex.: dias, %, pessoas, entregue/não entregue" },
      { key: "periodStart", label: "Início da medição", type: "date" },
      { key: "periodEnd", label: "Fim da medição", type: "date" },
      { key: "source", label: "Fonte do dado", required: true },
      { key: "owner", label: "Responsável", required: true },
      { key: "ownerEmail", label: "Email do responsável" },
      { key: "status", label: "Situação", type: "select", options: fixed(["Em dia", "Em risco", "Concluído"]) },
      { key: "riskReason", label: "Motivo do risco", type: "textarea" },
      { key: "nextAction", label: "Próxima ação", type: "textarea" },
      { key: "verification", label: "Critério de verificação", type: "textarea", hint: "Para resultados verificáveis, descreva qual evidência confirma a entrega." },
      { key: "changeReason", label: "Justificativa da alteração do alvo", type: "textarea" },
    ],
    progress: [
      { key: "priorityId", label: "Prioridade", type: "select", options: options("priority") },
      { key: "resultId", label: "Resultado", type: "select", options: options("result", (record) => !data.priorityId || record.data.priorityId === data.priorityId) },
      { key: "initiativeId", label: "Iniciativa", type: "select", options: options("initiative", (record) => !data.priorityId || record.data.priorityId === data.priorityId) },
      { key: "observedAt", label: "Data da atualização", type: "date", required: true },
      { key: "value", label: "Valor observado", hint: "Obrigatório ao atualizar um resultado. Não é uma porcentagem calculada automaticamente." },
      { key: "note", label: "O que avançou e qual é o contexto?", type: "textarea", required: true },
      { key: "status", label: "Situação", type: "select", options: fixed(["Em dia", "Em risco", "Bloqueado"]) },
      { key: "riskReason", label: "Motivo do risco ou bloqueio", type: "textarea" },
      { key: "nextAction", label: "Próxima ação", type: "textarea", hint: "Obrigatória quando estiver em risco ou bloqueado." },
    ],
    updateRequest: [
      { key: "cycleId", label: "Ciclo", type: "select", options: options("cycle"), required: true },
      { key: "reviewId", label: "Revisão", type: "select", options: options("review", (record) => !data.cycleId || record.data.cycleId === data.cycleId) },
      { key: "priorityId", label: "Prioridade", type: "select", options: options("priority", (record) => !data.cycleId || record.data.cycleId === data.cycleId), required: true },
      { key: "ownerEmail", label: "Email do responsável", required: true },
      { key: "due", label: "Prazo para responder", type: "date", required: true },
      { key: "message", label: "Pedido", type: "textarea" },
      { key: "response", label: "Resposta", type: "textarea" },
      { key: "status", label: "Situação", type: "select", options: fixed(["Pendente", "Respondida"]) },
    ],
    initiative: [
      { key: "priorityId", label: "Prioridade", type: "select", options: options("priority"), required: true },
      { key: "resultId", label: "Resultado relacionado", type: "select", options: options("result", (record) => !data.priorityId || record.data.priorityId === data.priorityId) },
      { key: "areaId", label: "Área", type: "select", options: options("area") },
      { key: "owner", label: "Responsável", required: true },
      { key: "ownerEmail", label: "Email do responsável" },
      { key: "team", label: "Equipe envolvida", placeholder: "Áreas ou pessoas que participam da entrega" },
      { key: "due", label: "Prazo", type: "date" },
      { key: "milestones", label: "Marcos principais", type: "textarea" },
      { key: "dependsOnId", label: "Depende de outra iniciativa", type: "select", options: options("initiative", (record) => !data.priorityId || linked(record.data.priorityId)?.data.cycleId === linked(data.priorityId)?.data.cycleId) },
      { key: "update", label: "Última atualização", type: "textarea" },
      { key: "status", label: "Situação", type: "select", options: fixed(["Planejada", "Em andamento", "Atenção", "Concluída"]) },
      { key: "riskReason", label: "Motivo da atenção", type: "textarea" },
      { key: "nextAction", label: "Próxima ação", type: "textarea" },
    ],
    risk: [
      { key: "priorityId", label: "Prioridade", type: "select", options: options("priority") },
      { key: "initiativeId", label: "Iniciativa", type: "select", options: options("initiative", (record) => !data.priorityId || record.data.priorityId === data.priorityId) },
      { key: "impact", label: "Impacto esperado", type: "textarea", required: true },
      { key: "owner", label: "Responsável pela resolução", required: true },
      { key: "ownerEmail", label: "Email do responsável" },
      { key: "due", label: "Data para resolver ou revisar", type: "date", required: true },
      { key: "dependencyAreaId", label: "Área da dependência", type: "select", options: options("area") },
      { key: "escalateTo", label: "Escalonar para" },
      { key: "nextAction", label: "Próxima ação", type: "textarea", required: true },
      { key: "status", label: "Situação", type: "select", options: fixed(["Aberto", "Em tratamento", "Resolvido"]) },
    ],
    decision: [
      { key: "priorityId", label: "Prioridade", type: "select", options: options("priority") },
      { key: "riskId", label: "Risco", type: "select", options: options("risk", (record) => !data.priorityId || record.data.priorityId === data.priorityId || linked(record.data.initiativeId)?.data.priorityId === data.priorityId) },
      { key: "reviewId", label: "Revisão", type: "select", options: options("review", (record) => !data.priorityId || record.data.cycleId === linked(data.priorityId)?.data.cycleId) },
      { key: "decisionMaker", label: "Quem precisa decidir", required: true },
      { key: "decision", label: "O que foi decidido", type: "textarea" },
      { key: "rationale", label: "Justificativa", type: "textarea" },
      { key: "owner", label: "Responsável pela execução" },
      { key: "ownerEmail", label: "Email do responsável" },
      { key: "due", label: "Prazo", type: "date", required: true },
      { key: "decidedAt", label: "Data da decisão", type: "date" },
      { key: "effect", label: "Efeito observado", type: "textarea" },
      { key: "status", label: "Situação", type: "select", options: fixed(["Pendente", "Em execução", "Concluída"]) },
    ],
    vacancy: [
      { key: "roleId", label: "Cargo de referência", type: "select", options: options("role"), required: true },
      { key: "priorityId", label: "Prioridade relacionada", type: "select", options: options("priority") },
      { key: "areaId", label: "Área", type: "select", options: options("area", (record) => !data.roleId || record.id === linked(data.roleId)?.data.areaId) },
      { key: "reason", label: "Justificativa da vaga", type: "textarea" },
      { key: "openingDate", label: "Data de abertura", type: "date" },
      { key: "interviewQuestions", label: "Perguntas estruturadas", type: "textarea", hint: "Use perguntas equivalentes para todas as pessoas candidatas." },
      { key: "interviewRubric", label: "Critérios de avaliação", type: "textarea", placeholder: "O que caracteriza uma resposta forte?" },
      { key: "status", label: "Etapa", type: "select", options: fixed(["Planejada", "Aberta", "Entrevistas", "Decisão", "Fechada"]) },
    ],
    teamTask: [
      { key: "personId", label: "Colaborador", type: "select", options: options("person", r => r.data.type === "Colaborador" && r.data.status !== "Desligado"), required: true },
      { key: "description", label: "O que precisa ser feito", type: "textarea", required: true },
      { key: "due", label: "Prazo", type: "date", required: true },
      { key: "status", label: "Situação", type: "select", options: fixed(["Pendente", "Em andamento", "Concluída", "Cancelada"]) },
      { key: "response", label: "Resposta ou entrega", type: "textarea" },
    ],
    person: [
      { key: "type", label: "Vínculo", type: "select", options: fixed(["Candidato", "Colaborador"]), required: true },
      ...(personType === "Candidato" ? [{ key: "vacancyId", label: "Vaga em análise", type: "select" as const, options: options("vacancy", record => !data.areaId || linked(record.data.roleId)?.data.areaId === data.areaId) }] : []),
      { key: "areaId", label: "Área", type: "select", options: options("area") },
      { key: "currentRoleId", label: "Cargo atual", type: "select", options: options("role", record => !data.areaId || record.data.areaId === data.areaId) },
      { key: "startDate", label: "Data de entrada", type: "date" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Telefone" },
      { key: "status", label: "Situação", type: "select", options: fixed(personType === "Candidato" ? ["Em análise", "Entrevista", "Oferta", "Contratado", "Não selecionado"] : ["Ativo", "Afastado", "Desligado"]) },
    ],
    assessment: [
      { key: "personId", label: "Pessoa", type: "select", options: records.filter((record) => record.kind === "person" && !record.archived_at && (record.data.type === personType || (data.type === "Contratação" && record.id === data.personId && !!(record.data.hiredAt || record.data.hiredFromVacancyId)))).map((record) => ({ value: record.id, label: record.title })), required: true },
      { key: "roleId", label: "Cargo avaliado", type: "select", options: options("role", record => { const vacancy = linked(linked(data.personId)?.data.vacancyId || data.vacancyId); return !vacancy || record.id === vacancy.data.roleId; }), required: true },
      ...(personType === "Candidato" ? [{ key: "vacancyId", label: "Vaga", type: "select" as const, options: options("vacancy", record => (!data.roleId || record.data.roleId === data.roleId) && (!linked(data.personId)?.data.vacancyId || record.id === linked(data.personId)?.data.vacancyId)) }] : []),
      { key: "type", label: "Tipo", type: "select", options: fixed(["Contratação", "Promoção"]), required: true },
      { key: "criteriaEvidence", label: "Critérios observados", type: "textarea", placeholder: "Relacione evidências às competências e resultados do cargo" },
      { key: "evidence", label: "Evidências", type: "textarea", required: true },
      { key: "gaps", label: "Pontos a desenvolver", type: "textarea" },
      { key: "interviewer", label: "Pessoa avaliadora" },
      { key: "assessedAt", label: "Data da avaliação", type: "date" },
      { key: "decision", label: "Decisão humana", type: "select", options: fixed(["Em análise", "Avançar", "Aguardar", "Não avançar"]) },
      { key: "nextStep", label: "Próxima ação", type: "textarea" },
    ],
    review: [
      { key: "cycleId", label: "Ciclo", type: "select", options: options("cycle"), required: true },
      { key: "meetingDate", label: "Data da reunião", type: "date", required: true },
      { key: "cadence", label: "Frequência", type: "select", options: fixed(["Semanal", "Quinzenal", "Mensal"]) },
      { key: "status", label: "Etapa", type: "select", options: fixed(["Preparação", "Concluída"]) },
      { key: "facilitator", label: "Responsável pela reunião" },
      { key: "summary", label: "Resumo da reunião", type: "textarea" },
      { key: "outcome", label: "Efeito das decisões anteriores", type: "textarea" },
      { key: "nextReview", label: "Próxima revisão", type: "date" },
    ],
    development: [
      { key: "personId", label: "Colaborador", type: "select", options: records.filter((record) => record.kind === "person" && !record.archived_at && record.data.type === "Colaborador").map((record) => ({ value: record.id, label: record.title })), required: true },
      { key: "roleId", label: "Cargo alvo", type: "select", options: options("role") },
      { key: "goal", label: "Objetivo de desenvolvimento", type: "textarea", required: true, placeholder: "Qual competência ou entrega precisa evoluir?" },
      { key: "action", label: "Ação prática", type: "textarea", required: true, placeholder: "O que a pessoa fará para alcançar esse objetivo?" },
      { key: "owner", label: "Responsável pelo acompanhamento", required: true },
      { key: "due", label: "Prazo", type: "date", required: true },
      { key: "status", label: "Situação", type: "select", options: fixed(["Planejado", "Em andamento", "Concluído"]) },
    ],
  };
  return fields[kind];
}
