"use client";

import { useState } from "react";
import { ArrowRight, BarChart3, BookOpenText, BriefcaseBusiness, Building2, CalendarDays, Check, CheckCircle2, GitBranch, LayoutDashboard, Lightbulb, Settings2, ShieldCheck, UsersRound, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { priorityFor } from "@/lib/traction-flow";
import type { TractionRecord } from "@/lib/traction-model";
import type { Section, SectionProps } from "./traction-types";

const active = (records: TractionRecord[], kind: TractionRecord["kind"]) => records.filter(item => item.kind === kind && !item.archived_at);
type Lesson = { section: Section; icon: typeof Target; title: string; purpose: string; steps: string[]; example: string; tip: string };
const lessons: Lesson[] = [
  { section: "team", icon: UsersRound, title: "Equipe", purpose: "Organize colaboradores, acessos e tarefas.", steps: ["Adicione a pessoa com área, cargo e email.", "O administrador escolhe se libera acesso e qual permissão concede.", "Copie o login criado e compartilhe com a pessoa. Nenhum email é enviado automaticamente.", "Atribua tarefas com prazo. Registre promoções com justificativa e data."], example: "Confirme uma contratação para incluir a pessoa na Equipe sem perder as entrevistas anteriores.", tip: "Cargo e permissão são diferentes: uma promoção muda o cargo; o acesso de administrador é concedido separadamente." },
  { section: "overview", icon: LayoutDashboard, title: "Início", purpose: "Encontre o que precisa da sua atenção hoje.", steps: ["Confira o ciclo atual e as prioridades.", "Abra as pendências e a fila de ações.", "Consulte responsável, prazo e situação antes de atualizar o registro."], example: "Ao encontrar uma ação atrasada, abra o registro e combine o próximo passo com o responsável.", tip: "Uma pendência precisa de uma ação concreta, não apenas de uma nova situação." },
  { section: "structure", icon: GitBranch, title: "Áreas e cargos", purpose: "Defina o que cada equipe e cargo deve entregar.", steps: ["Cadastre a área com missão e liderança.", "Crie o cargo vinculado à área: missão, nível, entregas e competências.", "Descreva critérios observáveis de sucesso e evolução."], example: "Cargo: Analista de RH. Entrega esperada: registrar cada entrevista com evidências ligadas aos critérios da vaga.", tip: "Use entregas e comportamentos observáveis. Evite descrições vagas como “ter perfil ideal”." },
  { section: "hiring", icon: BriefcaseBusiness, title: "Contratações", purpose: "Acompanhe a vaga e organize a decisão sobre cada candidato.", steps: ["Abra a vaga vinculada a um cargo e registre a necessidade.", "Prepare perguntas e critérios antes das entrevistas.", "Cadastre candidatos e registre avaliações com evidências.", "Documente a decisão humana e o próximo passo da candidatura."], example: "Evidência de organização: durante a entrevista, a pessoa explicou como priorizou tarefas e apresentou um exemplo verificável.", tip: "Compare pessoas pelos mesmos critérios do cargo. O sistema organiza a avaliação; a equipe decide." },
  { section: "promotions", icon: UsersRound, title: "Evolução interna", purpose: "Converse sobre promoção e desenvolvimento com contexto.", steps: ["Cadastre o colaborador com área e cargo atual.", "Escolha o cargo pretendido e confira seus critérios.", "Registre evidências, lacunas e a decisão responsável.", "Monte o plano de desenvolvimento com ação, responsável e prazo."], example: "Ação de desenvolvimento: conduzir a próxima reunião da equipe e registrar as decisões, com acompanhamento do gestor e prazo combinado.", tip: "Diferencie o desempenho no cargo atual das exigências do cargo pretendido." },
  { section: "planning", icon: Target, title: "Plano do ciclo", purpose: "Conecte a direção da empresa ao trabalho do período.", steps: ["Crie um ciclo com início, fim e objetivo estratégico.", "Vincule prioridades ao objetivo e defina responsáveis e prazos.", "Em cada resultado, informe indicador, valor inicial, alvo, período e fonte.", "Crie iniciativas para executar e registre atualizações do avanço."], example: "Objetivo: melhorar a experiência de contratação. Prioridade: organizar entrevistas. Indicador: tempo entre entrevista e devolutiva, medido pelos registros reais.", tip: "Objetivo é a direção; prioridade é o foco; iniciativa é a ação; resultado é a medida do que mudou." },
  { section: "reviews", icon: CalendarDays, title: "Reuniões e decisões", purpose: "Transforme a conversa em compromissos acompanháveis.", steps: ["Agende a revisão do ciclo e confira a pauta.", "Revise avanços, riscos e decisões pendentes.", "Registre a decisão, o motivo, o responsável e o prazo.", "Na próxima reunião, confira o efeito e os compromissos anteriores."], example: "Decisão: revisar as perguntas de entrevista. Responsável: liderança de RH. Prazo: data acordada. Efeito a acompanhar: avaliações com evidências mais claras.", tip: "Feche cada decisão com responsável e próximo passo. Consulte o histórico antes de repetir a discussão." },
  { section: "results", icon: BarChart3, title: "Resultados", purpose: "Entenda o que os registros da empresa mostram.", steps: ["Confira o período e a cobertura dos dados.", "Compare valores observados, situação inicial e alvos.", "Abra as evidências e revise as lacunas indicadas.", "Use a leitura para definir próximas ações no ciclo."], example: "Sem uma atualização do indicador, registre o valor observado e a fonte antes de concluir que houve avanço.", tip: "Dado ausente não é zero. O resumo gratuito é curto; o relatório completo aprofunda os registros conforme o acesso da empresa." },
  { section: "admin", icon: Settings2, title: "Administração", purpose: "Configure a empresa, sua marca e os acessos.", steps: ["Revise nome e contatos em Empresa.", "Aplique logo e cores em Identidade visual e confira a leitura da prévia.", "Em Pessoas e acessos, confira o alcance da função antes de salvar.", "Use Dados e arquivo para consultar registros arquivados e exportar dados autorizados."], example: "Uma pessoa que só consulta o plano pode usar o papel Leitor; a Administração fica com quem precisa configurar o espaço.", tip: "Cada pessoa deve usar seu próprio acesso. Confira a empresa selecionada antes de editar ou exportar." },
];
const practices = [
  { title: "Critério antes da avaliação", text: "Defina entregas e competências no cargo antes de entrevistar ou avaliar uma promoção.", section: "structure" as Section, action: "Consultar cargos" },
  { title: "Evidência antes da conclusão", text: "Registre o que foi observado, quando aconteceu e a fonte. Diferencie fato, interpretação e informação ainda ausente.", section: "hiring" as Section, action: "Consultar avaliações" },
  { title: "Ação com dono e prazo", text: "Troque “melhorar a comunicação” por uma atividade concreta, com responsável e data para acompanhar.", section: "planning" as Section, action: "Abrir plano do ciclo" },
  { title: "Atualize antes da reunião", text: "Registre avanços e impedimentos antes da revisão. Use o encontro para resolver pendências e decidir próximos passos.", section: "reviews" as Section, action: "Preparar reunião" },
  { title: "Resultados com período e fonte", text: "Compare medidas do mesmo período e unidade. Deixe o campo pendente quando ainda não houver um valor observado.", section: "results" as Section, action: "Consultar resultados" },
  { title: "Decisões feitas por pessoas", text: "Use o histórico para apoiar a conversa. Registre quem decidiu e por quê; nenhum relatório substitui essa responsabilidade.", section: "promotions" as Section, action: "Abrir evolução interna" },
];
const questions = [
  ["Preciso criar uma empresa para aprender a usar?", "Não. Este guia pode ser consultado antes da configuração. Para salvar dados, abra uma empresa autorizada. Se ela já existe, peça acesso ao administrador em vez de criar outra."],
  ["Por que meu painel está vazio?", "Cada empresa começa com seus próprios registros. Cadastre áreas e cargos ou abra um ciclo. Sem dados, o sistema mostra o que falta; não cria resultados fictícios."],
  ["Por que não vejo todos os módulos?", "Os módulos seguem a função atribuída à sua conta. Se precisa de outra área, peça ao administrador que revise sua permissão. O acesso master pode consultar as empresas, mas os registros continuam vinculados a uma empresa selecionada."],
  ["O sistema escolhe quem contratar ou promover?", "Não. Ele organiza cargos, critérios, entrevistas, evidências e planos. A decisão é feita e registrada pela equipe responsável."],
  ["O que muda no relatório completo?", "O gratuito apresenta uma síntese curta. O completo aprofunda os registros de estrutura, execução, avaliações, desenvolvimento, riscos, decisões e histórico, conforme o acesso contratado."],
  ["Como retomo uma pendência?", "Abra Início e consulte a fila de ações. Acesse o registro, confira responsável e prazo e atualize o próximo passo. Decisões de reuniões também podem ser consultadas em Reuniões e decisões."],
];

export function TractionGuide({ records, workspace, onNavigate, onCreateOrganization }: SectionProps) {
  const [tab, setTab] = useState("start");
  const [lessonId, setLessonId] = useState<Section>("structure");
  const lesson = lessons.find(item => item.section === lessonId)!;
  const canOpen = (section: Section) => section === "admin" ? workspace?.role === "admin" : ["hiring", "promotions"].includes(section) ? !workspace || ["admin", "gestor"].includes(workspace.role) : true;
  const cycle = active(records, "cycle").find(item => item.data.status === "Ativo") || active(records, "cycle").find(item => item.data.status === "Planejado");
  const priorities = active(records, "priority").filter(item => !!cycle && item.data.cycleId === cycle.id);
  const priorityIds = new Set(priorities.map(item => item.id));
  const steps = [
    { title: "Abra a empresa certa", detail: workspace ? `Espaço atual: ${workspace.organization.name}.` : "Crie o espaço da sua empresa ou peça acesso se ela já está cadastrada.", done: !!workspace, section: "overview" as Section, action: workspace ? "Abrir início" : "Criar empresa" },
    { title: "Organize áreas e cargos", detail: workspace ? `${active(records, "area").length} áreas e ${active(records, "role").length} cargos visíveis no seu acesso.` : "Descreva equipes, cargos e critérios que servirão de base para as avaliações.", done: active(records, "area").length > 0 && active(records, "role").length > 0, section: "structure" as Section, action: "Abrir áreas e cargos" },
    { title: "Defina o foco e a medida", detail: cycle ? `${cycle.title}: ${priorities.length} ${priorities.length === 1 ? "prioridade visível" : "prioridades visíveis"}. Confira objetivos e indicadores no plano.` : "Escolha o período, o objetivo, as prioridades e como medir os resultados.", done: !!cycle && active(records, "objective").some(item => item.data.cycleId === cycle.id) && priorities.length > 0 && active(records, "result").some(item => priorityIds.has(item.data.priorityId)), section: "planning" as Section, action: "Abrir plano do ciclo" },
    { title: "Acompanhe e revise", detail: "Atualize o avanço, registre impedimentos e combine os próximos passos na reunião.", done: !!cycle && active(records, "progress").some(item => priorityIds.has(priorityFor(item, records))) && active(records, "review").some(item => item.data.cycleId === cycle.id), section: "reviews" as Section, action: "Abrir reuniões" },
  ];
  function chooseLesson(section: Section) { setLessonId(section); setTab("modules"); }

  return <div className="practice-page">
    <section className="practice-intro"><div><span className="section-label">PARA QUE SERVE O SYNKY TRACTION?</span><h2>Organize o trabalho.<br />Dê contexto às decisões de pessoas.</h2><p>Um espaço para definir cargos, conduzir contratações, acompanhar desenvolvimento e ver o avanço das prioridades da empresa.</p><span className="practice-human">O sistema organiza. Sua equipe decide.</span></div><div className="practice-intents" aria-label="Escolha o que você quer fazer"><button onClick={() => chooseLesson("hiring")}><BriefcaseBusiness size={22} /><span><strong>Quero contratar</strong><small>Vaga, entrevista e avaliação</small></span><ArrowRight size={17} /></button><button onClick={() => chooseLesson("promotions")}><UsersRound size={22} /><span><strong>Quero desenvolver a equipe</strong><small>Cargo, evidências e plano de ação</small></span><ArrowRight size={17} /></button><button onClick={() => chooseLesson("planning")}><Target size={22} /><span><strong>Quero acompanhar o trabalho</strong><small>Prioridades, prazos e resultados</small></span><ArrowRight size={17} /></button></div></section>
    <Tabs value={tab} onValueChange={setTab} className="practice-tabs-root"><TabsList className="practice-tabs" aria-label="Conteúdo de boas práticas"><TabsTrigger value="start">Por onde começar</TabsTrigger><TabsTrigger value="modules">Usar os módulos</TabsTrigger><TabsTrigger value="practices">Boas práticas</TabsTrigger><TabsTrigger value="questions">Dúvidas</TabsTrigger></TabsList>
      <TabsContent value="start"><section className="practice-panel"><div className="practice-panel-head"><div><span className="section-label">PRIMEIROS PASSOS</span><h2>Monte a base uma vez. Use no dia a dia.</h2><p>{workspace ? "Checklist dos registros visíveis na empresa selecionada." : "Você pode explorar este guia antes de cadastrar sua empresa."}</p></div>{workspace && <span className="practice-progress">{steps.filter(item => item.done).length} de {steps.length} etapas com registros</span>}</div><ol className="practice-checklist">{steps.map((step, index) => <li key={step.title}><span className={`practice-step-marker ${step.done ? "done" : ""}`}>{step.done ? <Check size={18} /> : index + 1}</span><div><strong>{step.title}</strong><p>{step.detail}</p><small>{step.done ? "Registros encontrados · revise a qualidade" : "A preparar"}</small></div><Button size="sm" variant="outline" onClick={() => !workspace && index === 0 ? onCreateOrganization() : onNavigate(step.section)}>{step.action}<ArrowRight size={15} /></Button></li>)}</ol><div className="practice-tip"><Lightbulb size={20} /><p><strong>Comece pela necessidade da empresa.</strong> Para contratar, organize o cargo e abra a vaga. Para acompanhar a execução, defina o ciclo. As etapas indicam registros existentes, não uma avaliação de desempenho.</p></div></section></TabsContent>
      <TabsContent value="modules"><div className="practice-learning"><nav className="practice-module-list" aria-label="Escolher módulo para aprender">{lessons.map(item => <button key={item.section} aria-pressed={lessonId === item.section} onClick={() => setLessonId(item.section)}><item.icon size={19} /><span>{item.title}</span><ArrowRight size={15} /></button>)}</nav><article className="practice-panel practice-lesson" aria-labelledby="practice-lesson-title"><span className="section-label">COMO USAR</span><h2 id="practice-lesson-title">{lesson.title}</h2><p className="practice-lesson-purpose">{lesson.purpose}</p><ol className="practice-lesson-steps">{lesson.steps.map((step,index) => <li key={step}><span>{index + 1}</span><p>{step}</p></li>)}</ol><div className="practice-example"><span>EXEMPLO ILUSTRATIVO · NÃO É UM REGISTRO DA EMPRESA</span><p>{lesson.example}</p></div><div className="practice-tip"><Lightbulb size={20} /><p>{lesson.tip}</p></div>{canOpen(lesson.section) ? <Button className="action-primary" onClick={() => onNavigate(lesson.section)}>Abrir {lesson.title}<ArrowRight size={16} /></Button> : <p className="practice-permission"><ShieldCheck size={17} />{workspace ? "O acesso a este módulo depende da função atribuída à sua conta." : "Abra uma empresa com permissão de administrador para aplicar estas configurações."}</p>}</article></div></TabsContent>
      <TabsContent value="practices"><section className="practice-panel"><div className="practice-panel-head"><div><span className="section-label">NO DIA A DIA</span><h2>Registros que ajudam a agir.</h2><p>Pequenos cuidados que deixam o trabalho e as decisões mais claros.</p></div></div><div className="practice-rules">{practices.map(item => <article key={item.title}><CheckCircle2 size={21} /><h3>{item.title}</h3><p>{item.text}</p>{canOpen(item.section) && <button onClick={() => onNavigate(item.section)}>{item.action}<ArrowRight size={15} /></button>}</article>)}</div></section></TabsContent>
      <TabsContent value="questions"><section className="practice-panel"><div className="practice-panel-head"><div><span className="section-label">AJUDA RÁPIDA</span><h2>Se ficou alguma dúvida.</h2></div><BookOpenText size={22} /></div><div className="practice-questions">{questions.map(([question,answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section></TabsContent>
    </Tabs>
    <div className="practice-footer"><Building2 size={17} /><span>{workspace ? `Orientações para ${workspace.organization.name}. Os atalhos respeitam seu acesso.` : "Guia de uso: os exemplos não criam dados nem alteram sua empresa."}</span></div>
  </div>;
}
