"use client";

import { ArrowRight, Building2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Section, SectionProps } from "./traction-types";

const modules: Record<"planning" | "structure" | "hiring" | "promotions" | "reviews" | "results", { eyebrow: string; title: string; description: string; steps: { title: string; detail: string }[]; next: Section; nextLabel: string }> = {
  planning: { eyebrow: "TRANSFORME O PLANO EM AÇÃO", title: "Da direção da empresa ao trabalho de cada semana", description: "Um ciclo conecta o objetivo da empresa às prioridades, medidas, responsáveis e ações. Assim, cada reunião parte do que realmente aconteceu.", steps: [{ title: "Escolha a direção", detail: "Abra um ciclo e descreva o objetivo que reúne a equipe." }, { title: "Defina foco e medida", detail: "Escolha prioridades, resultado esperado, indicador, alvo e responsável." }, { title: "Execute e revise", detail: "Registre avanços e riscos; use as revisões para decidir o próximo passo." }], next: "reviews", nextLabel: "Conhecer revisões" },
  structure: { eyebrow: "COMECE PELA BASE", title: "Desenhe como o trabalho acontece", description: "Uma área define responsabilidades. Um cargo define missão, entregas, competências e critérios de evolução.", steps: [{ title: "Mapeie as áreas", detail: "Registre a missão de cada equipe e quem responde por ela." }, { title: "Descreva os cargos", detail: "Defina resultados, competências e critérios claros por nível." }, { title: "Use a estrutura", detail: "Conecte cargos a vagas, avaliações e desenvolvimento." }], next: "hiring", nextLabel: "Explorar contratações" },
  hiring: { eyebrow: "CONTRATE COM CRITÉRIOS", title: "Da vaga à decisão documentada", description: "Prepare a avaliação antes das entrevistas e compare pessoas pelos mesmos critérios do cargo.", steps: [{ title: "Abra a vaga", detail: "Vincule um cargo e justifique a necessidade." }, { title: "Prepare a entrevista", detail: "Registre perguntas equivalentes e critérios de comparação." }, { title: "Avalie evidências", detail: "Documente observações e a decisão humana responsável." }], next: "structure", nextLabel: "Ver estrutura" },
  promotions: { eyebrow: "EVOLUÇÃO INTERNA", title: "Torne a promoção explicável", description: "Converse sobre resultados observados, critérios do cargo alvo e ações concretas de desenvolvimento.", steps: [{ title: "Cadastre a pessoa", detail: "Associe área e cargo atual." }, { title: "Compare com o cargo alvo", detail: "Registre evidências e lacunas com os mesmos critérios." }, { title: "Acompanhe o plano", detail: "Defina ações, responsável e prazo após a conversa." }], next: "structure", nextLabel: "Ver critérios dos cargos" },
  reviews: { eyebrow: "RITMO DE GESTÃO", title: "Uma reunião com pauta e consequência", description: "As revisões usam os registros do ciclo para mostrar impedimentos, solicitar atualizações e documentar decisões.", steps: [{ title: "Defina um ciclo", detail: "Escolha o período e as prioridades que serão acompanhadas." }, { title: "Prepare a pauta", detail: "Veja riscos, atrasos, lacunas e atualizações pendentes." }, { title: "Feche o combinado", detail: "Registre decisões, responsáveis, prazos e o efeito na próxima reunião." }], next: "planning", nextLabel: "Explorar planejamento" },
  results: { eyebrow: "RESULTADOS SEM SIMULAÇÃO", title: "Uma leitura que nasce dos registros", description: "O painel cruza estrutura, execução e decisões da empresa. Campos ausentes aparecem como pendências, nunca como conquistas presumidas.", steps: [{ title: "Registre a base", detail: "Estruture cargos, ciclo e prioridades." }, { title: "Alimente os indicadores", detail: "Defina alvo, fonte e valores observados ao longo do tempo." }, { title: "Aja sobre a análise", detail: "Abra pendências, acompanhe revisões e consulte o histórico completo no plano pago." }], next: "planning", nextLabel: "Explorar planejamento" },
};

export function ModuleStart({ module, onCreateOrganization, onNavigate }: Pick<SectionProps, "onCreateOrganization" | "onNavigate"> & { module: keyof typeof modules }) {
  const config = modules[module];
  return <section className="module-start" aria-label={`Como funciona: ${module}`}>
    <div className="module-start-main"><span className="section-label">{config.eyebrow}</span><h2>{config.title}</h2><p>{config.description}</p><div className="module-start-actions"><Button className="action-primary" onClick={onCreateOrganization}><Building2 size={16} /> Criar empresa para começar</Button><Button variant="outline" onClick={() => onNavigate(config.next)}>{config.nextLabel} <ArrowRight size={15} /></Button></div><small>Esta é uma prévia do fluxo. Nenhum resultado ou registro foi criado.</small></div>
    <ol className="module-start-steps">{config.steps.map((step, index) => <li key={step.title}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{step.title}</strong><p>{step.detail}</p></div></li>)}</ol>
  </section>;
}
